# Generated by Django 3.2.11 on 2022-03-10 00:23

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_auto_20220305_2240'),
    ]

    operations = [
        migrations.AddField(
            model_name='shippingaddress',
            name='postal_code',
            field=models.CharField(default='', max_length=6, validators=[django.core.validators.RegexValidator('^(?!.{0,7}[DFIOQU])[A-VXY]\\d[A-Z]\\d[A-Z]\\d$', 'Invalid Canadian Postal Code.')]),
        ),
        migrations.AlterField(
            model_name='shippingaddress',
            name='province',
            field=models.CharField(choices=[('AB', 'AB'), ('BC', 'BC'), ('MB', 'MB'), ('NB', 'NB'), ('NS', 'NS'), ('NL', 'NL'), ('ON', 'ON'), ('PE', 'PE'), ('QC', 'QC'), ('SK', 'SK')], max_length=2),
        ),
        migrations.AlterField(
            model_name='user',
            name='credit_card',
            field=models.CharField(default='', max_length=16, validators=[django.core.validators.RegexValidator('^\\d{16}$', 'Credit card number must be 16 digit numbers.')]),
        ),
    ]
