# Generated by Django 3.2.11 on 2022-02-12 21:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0014_alter_recipe_label'),
        ('users', '0002_alter_shippingaddress_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='fav_recipes',
            field=models.ManyToManyField(blank=True, to='recipes.Recipe'),
        ),
    ]
