# Generated by Django 3.2.11 on 2022-02-19 00:34

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_alter_user_fav_recipes'),
    ]

    operations = [
        migrations.RenameField(
            model_name='shippingaddress',
            old_name='address2',
            new_name='address',
        ),
        migrations.RemoveField(
            model_name='shippingaddress',
            name='address1',
        ),
        migrations.AlterField(
            model_name='shippingaddress',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shipping_address', to=settings.AUTH_USER_MODEL),
        ),
    ]
