image: docker

services:
  - docker:dind

variables:
  DEBUG: 1
  SECRETE_KEY: foo
  DJANGO_ALLOWED_HOSTS: localhost 127.0.0.1 [::1]
  POSTGRES_DB: ece651
  POSTGRES_USER: ece651
  POSTGRES_PASSWORD: ece651
  SQL_ENGINE: django.db.backends.postgresql
  SQL_DATABASE: ece651
  SQL_USER: ece651
  SQL_PASSWORD: ece651
  SQL_HOST: db
  SQL_PORT: 5432

stages:
  - pre-build
  - build
  - test
  - dev-deploy

pre-build-job:
  stage: pre-build
  script:
    - echo "DEBUG=$DEBUG" >> .env
    - echo "SECRET_KEY=$SECRET_KEY" >> .env
    - echo "DJANGO_ALLOWED_HOSTS=$DJANGO_ALLOWED_HOSTS" >> .env
    - echo "POSTGRES_USER=$POSTGRES_USER" >> .env
    - echo "POSTGRES_PASSWORD=$POSTGRES_PASSWORD" >> .env
    - echo "POSTGRES_DB=$POSTGRES_DB" >> .env
    - echo "SQL_ENGINE=$SQL_ENGINE" >> .env
    - echo "SQL_DATABASE=$SQL_DATABASE" >> .env
    - echo "SQL_USER=$SQL_USER" >> .env
    - echo "SQL_PASSWORD=$SQL_PASSWORD" >> .env
    - echo "SQL_HOST=$SQL_HOST" >> .env
    - echo "SQL_PORT=$SQL_PORT" >> .env
  artifacts:
    reports:
      dotenv: .env

build-job:
  stage: build
  only:
    - master
  script:
    - echo Building project...
    - echo "DEBUG=$DEBUG" >> .env
    - echo "SECRET_KEY=$SECRET_KEY" >> .env
    - echo "DJANGO_ALLOWED_HOSTS=$DJANGO_ALLOWED_HOSTS" >> .env
    - echo "POSTGRES_USER=$POSTGRES_USER" >> .env
    - echo "POSTGRES_PASSWORD=$POSTGRES_PASSWORD" >> .env
    - echo "POSTGRES_DB=$POSTGRES_DB" >> .env
    - echo "SQL_ENGINE=$SQL_ENGINE" >> .env
    - echo "SQL_DATABASE=$SQL_DATABASE" >> .env
    - echo "SQL_USER=$SQL_USER" >> .env
    - echo "SQL_PASSWORD=$SQL_PASSWORD" >> .env
    - echo "SQL_HOST=$SQL_HOST" >> .env
    - echo "SQL_PORT=$SQL_PORT" >> .env
    - sudo ./leh build
    - echo Project built sccussfully
  tags:
    - ece651

unit-test-integration-test-job:
  stage: test
  only:
    - master
  script:
    - echo Running unit tests and integration tests....
    - echo "DEBUG=$DEBUG" >> .env
    - echo "SECRET_KEY=$SECRET_KEY" >> .env
    - echo "DJANGO_ALLOWED_HOSTS=$DJANGO_ALLOWED_HOSTS" >> .env
    - echo "POSTGRES_USER=$POSTGRES_USER" >> .env
    - echo "POSTGRES_PASSWORD=$POSTGRES_PASSWORD" >> .env
    - echo "POSTGRES_DB=$POSTGRES_DB" >> .env
    - echo "SQL_ENGINE=$SQL_ENGINE" >> .env
    - echo "SQL_DATABASE=$SQL_DATABASE" >> .env
    - echo "SQL_USER=$SQL_USER" >> .env
    - echo "SQL_PASSWORD=$SQL_PASSWORD" >> .env
    - echo "SQL_HOST=$SQL_HOST" >> .env
    - echo "SQL_PORT=$SQL_PORT" >> .env
    - sudo docker-compose -f docker-compose.yml run --rm app python3 manage.py migrate
    - sudo docker-compose -f docker-compose.yml run --rm app python3 manage.py test
    - echo "Unit tests & intergation tests passed"
  tags:
    - ece651

system-test-job:
  stage: test
  only:
    - master
  script:
    - echo Running system tests....
    - echo "DEBUG=$DEBUG" >> .env
    - echo "SECRET_KEY=$SECRET_KEY" >> .env
    - echo "DJANGO_ALLOWED_HOSTS=$DJANGO_ALLOWED_HOSTS" >> .env
    - echo "POSTGRES_USER=$POSTGRES_USER" >> .env
    - echo "POSTGRES_PASSWORD=$POSTGRES_PASSWORD" >> .env
    - echo "POSTGRES_DB=$POSTGRES_DB" >> .env
    - echo "SQL_ENGINE=$SQL_ENGINE" >> .env
    - echo "SQL_DATABASE=$SQL_DATABASE" >> .env
    - echo "SQL_USER=$SQL_USER" >> .env
    - echo "SQL_PASSWORD=$SQL_PASSWORD" >> .env
    - echo "SQL_HOST=$SQL_HOST" >> .env
    - echo "SQL_PORT=$SQL_PORT" >> .env
    - sudo docker-compose -f docker-compose.yml run --rm app python3 manage.py migrate
    - sudo docker-compose -f docker-compose.yml run --rm app python3 manage.py test
    - echo "System tests passed"
  tags:
    - ece651

deploy-job:
  stage: dev-deploy
  only:
    - master
  script:
    - echo Deploying to the remote server...
    - echo "DEBUG=$DEBUG" >> .env
    - echo "SECRET_KEY=$SECRET_KEY" >> .env
    - echo "DJANGO_ALLOWED_HOSTS=$DJANGO_ALLOWED_HOSTS" >> .env
    - echo "POSTGRES_USER=$POSTGRES_USER" >> .env
    - echo "POSTGRES_PASSWORD=$POSTGRES_PASSWORD" >> .env
    - echo "POSTGRES_DB=$POSTGRES_DB" >> .env
    - echo "SQL_ENGINE=$SQL_ENGINE" >> .env
    - echo "SQL_DATABASE=$SQL_DATABASE" >> .env
    - echo "SQL_USER=$SQL_USER" >> .env
    - echo "SQL_PASSWORD=$SQL_PASSWORD" >> .env
    - echo "SQL_HOST=$SQL_HOST" >> .env
    - echo "SQL_PORT=$SQL_PORT" >> .env
    - sudo docker-compose -f docker-compose.yml build -d
    - sudo docker-compose up -d
    - sudo docker-compose logs app
    - sudo docker rmi $(sudo docker images -f "dangling=true" -q)
    - echo Deoloyed to the remote server successfully
  tags:
    - ece651
  environment: deployment
  when: manual
