version: '3.8'

services:
  app:
    environment:
      SELENIUM_HOST: http://selenium:4444/wd/hub
      TEST_SELENIUM: 'yes'
    build: .
    command: ./entrypoint.sh
    volumes:
      - ./:/code/
    ports:
      - 8000:8000
      - 8001:8001
    depends_on:
      - db
      - selenium
      - lehstore
    env_file:
      - ./.env
    networks:
      main:
        aliases:
          - app

  db:
    image: postgres:14
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    ports:
      - "5432:5432"
    env_file:
      - ./.env
    networks:
      main:
        aliases:
          - db

  selenium:
    image: selenium/standalone-chrome-debug
    ports:
      - "5901:5900"
    shm_size: 2g
    networks:
      main:
        aliases:
          - selenium

  lehstore:
    container_name: lehstore
    build: ./lehfront
    ports:
      - "4200:80"
    networks:
      main:
        aliases:
          - lehstore

volumes:
  postgres_data:

networks:
  main: