# Generated by Django 3.2.11 on 2022-02-06 22:08

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0008_recipe_image_url'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='recipe',
            name='recipe_id',
        ),
        migrations.AddField(
            model_name='recipe',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
            preserve_default=False,
        ),
    ]
