# Generated by Django 3.2.11 on 2022-02-11 21:51

from django.db import migrations, models
import django.utils.timezone
import django_better_admin_arrayfield.models.fields


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0010_auto_20220211_1943'),
    ]

    operations = [
        migrations.RenameField(
            model_name='recipe',
            old_name='total_views',
            new_name='total_reviews',
        ),
        migrations.AddField(
            model_name='recipe',
            name='slug',
            field=models.SlugField(default=django.utils.timezone.now, max_length=255),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='recipe',
            name='instructions',
            field=django_better_admin_arrayfield.models.fields.ArrayField(base_field=models.CharField(max_length=200), blank=True, null=True, size=None),
        ),
    ]
