# Generated by Django 3.2.11 on 2022-02-11 22:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0012_auto_20220211_2208'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipe',
            name='label',
            field=models.ManyToManyField(blank=True, null=True, to='recipes.Label'),
        ),
    ]
