# Generated by Django 3.2.11 on 2022-02-12 21:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0013_alter_recipe_label'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipe',
            name='label',
            field=models.ManyToManyField(blank=True, to='recipes.Label'),
        ),
    ]
