# Generated by Django 3.2.11 on 2022-02-21 20:30

from django.db import migrations, models
import django_better_admin_arrayfield.models.fields


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0015_auto_20220218_1954'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipe',
            name='ingredients_detail',
            field=django_better_admin_arrayfield.models.fields.ArrayField(base_field=models.CharField(max_length=200), blank=True, null=True, size=None),
        ),
    ]
