# Generated by Django 4.0.1 on 2022-01-27 05:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order_product_list',
            name='quantity',
            field=models.IntegerField(),
        ),
    ]
