# Generated by Django 4.0.1 on 2022-01-29 16:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Nutrients',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50, verbose_name='nutrient name')),
                ('measure', models.CharField(choices=[('g', 'gram'), ('mg', 'milligram'), ('%dv', 'daily value')], max_length=30, verbose_name='nutrient measurement')),
            ],
        ),
        migrations.CreateModel(
            name='Product_Nutrients',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contains', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='nutrients quantity')),
                ('nutrient_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='products.nutrients')),
            ],
        ),
        migrations.CreateModel(
            name='Product_Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='category name')),
            ],
        ),
        migrations.CreateModel(
            name='Products_Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='category name')),
            ],
        ),
        migrations.CreateModel(
            name='Products',
            fields=[
                ('products_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=120, verbose_name='product name')),
                ('description', models.TextField(blank=True)),
                ('si_unit', models.CharField(blank=True, choices=[('g', 'gram'), ('kg', 'kilogram'), ('ml', 'ml'), ('L', 'liter')], max_length=10, verbose_name='product si unit')),
                ('quantity_in_si_unit', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='si quantity')),
                ('p_unit', models.CharField(blank=True, choices=[('L', 'liter'), ('bag', 'bag'), ('bottle', 'bottle'), ('box', 'box'), ('carton', 'carton'), ('item', 'item'), ('pack', 'pack')], max_length=10, verbose_name='product unit')),
                ('is_active', models.BooleanField(default=False)),
                ('unit_quantity', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='unit quantity')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='price')),
                ('stock', models.IntegerField()),
                ('on_promotion', models.BooleanField(default=False)),
                ('in_recipe', models.BooleanField(default=False)),
                ('last_order_timestamp', models.DateTimeField(auto_now=True)),
                ('image', models.URLField(max_length=500)),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='products.products_category')),
                ('labels', models.ManyToManyField(to='products.Product_Tag')),
                ('nutrients', models.ManyToManyField(through='products.Product_Nutrients', to='products.Nutrients')),
            ],
        ),
        migrations.AddField(
            model_name='product_nutrients',
            name='product_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.products'),
        ),
    ]
