# Generated by Django 4.0.1 on 2022-01-25 16:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product_Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='category name')),
            ],
        ),
        migrations.AddField(
            model_name='products',
            name='labels',
            field=models.ManyToManyField(to='products.Product_Tag'),
        ),
    ]
