# Generated by Django 3.2.11 on 2022-02-04 14:39

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_alter_producttag_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='producttag',
            name='slug',
            field=models.SlugField(default=django.utils.timezone.now, max_length=255, unique=True),
            preserve_default=False,
        ),
    ]
