# Generated by Django 3.2.11 on 2022-02-06 16:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0005_custom_migrations'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='image',
            new_name='image_url',
        ),
    ]
