# Generated by Django 3.2.11 on 2022-02-06 22:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0006_rename_image_product_image_url'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='product',
            options={},
        ),
    ]
