# Generated by Django 3.2.11 on 2022-02-11 18:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0009_auto_20220210_0352'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productnutrient',
            name='nutrient_id',
        ),
        migrations.RemoveField(
            model_name='productnutrient',
            name='product_id',
        ),
        migrations.RemoveField(
            model_name='product',
            name='nutrients',
        ),
        migrations.DeleteModel(
            name='Nutrient',
        ),
        migrations.DeleteModel(
            name='ProductNutrient',
        ),
    ]
