# Generated by Django 3.2.11 on 2022-02-11 20:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0010_auto_20220211_1801'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='labels',
            field=models.ManyToManyField(blank=True, null=True, to='products.ProductTag'),
        ),
        migrations.AlterField(
            model_name='product',
            name='si_unit',
            field=models.CharField(blank=True, choices=[('g', 'gram'), ('kg', 'kilogram'), ('ml', 'ml'), ('L', 'liter'), ('lb', 'pound')], max_length=10, verbose_name='product si unit'),
        ),
    ]
