# Generated by Django 3.2.11 on 2022-02-12 21:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0011_auto_20220211_2013'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='labels',
            field=models.ManyToManyField(blank=True, to='products.ProductTag'),
        ),
    ]
