# Generated by Django 3.2.11 on 2022-02-25 21:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0012_alter_product_labels'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productcategory',
            name='slug',
            field=models.SlugField(max_length=255),
        ),
        migrations.AlterField(
            model_name='producttag',
            name='slug',
            field=models.SlugField(max_length=255),
        ),
    ]
